//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neptuo.Templates
{
    
    public sealed class View_B3FB932CB3BBED93A72876CB64C25B2BDE4D0C0E : Neptuo.TemplateEngine.Web.GeneratedViewBase, System.IDisposable
    {
        protected override void CreateViewPageControls(Neptuo.Templates.IViewPage viewPage)
        {
            this.Content.Add(this.field82_Create());
            this.Content.Add("\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n    <meta charset=\"utf-8\" " +
                    "/>\r\n    <title>\r\n        ");
            this.Content.Add(this.field83_Create());
            this.Content.Add("\r\n        ");
            this.Content.Add(this.field84_Create());
            this.Content.Add("\r\n        TemplateEngine\r\n    ");
            this.Content.Add(@"</title>
    
    <link href=""../../Design/Styles/bootstrap.css"" rel=""stylesheet"" />
    <link href=""../../Design/Styles/bootstrap-theme.css"" rel=""stylesheet"" />
    <link href=""../../Design/Styles/My/Common.css"" rel=""stylesheet"" />
    <link href=""../../Design/Styles/My/Layout.css"" rel=""stylesheet"" />

    ");
            this.Content.Add(this.field86_Create());
            this.Content.Add("\r\n\r\n");
            this.Content.Add("</head>\r\n<body>\r\n\r\n    <div class=\"navbar navbar-fixed-top navbar-main\">\r\n       " +
                    " <div class=\"navbar-header\">\r\n            ");
            this.Content.Add(this.field87_Create());
            this.Content.Add("\r\n        ");
            this.Content.Add("</div>\r\n        <ul class=\"nav navbar-nav\">\r\n            <li>\r\n                ");
            this.Content.Add(this.field88_Create());
            this.Content.Add("\r\n            ");
            this.Content.Add("</li>\r\n            <li>\r\n                ");
            this.Content.Add(this.field90_Create());
            this.Content.Add("\r\n            ");
            this.Content.Add("</li>\r\n        ");
            this.Content.Add("</ul>\r\n    ");
            this.Content.Add("</div>\r\n\r\n    <div class=\"body-container\">\r\n        ");
            this.Content.Add(this.field92_Create());
            this.Content.Add("\r\n        <div class=\"body\">\r\n            ");
            this.Content.Add(this.field95_Create());
            this.Content.Add("\r\n            ");
            this.Content.Add(this.field96_Create());
            this.Content.Add("\r\n        ");
            this.Content.Add("</div>\r\n    ");
            this.Content.Add("</div>\r\n\r\n    <footer class=\"navbar\">\r\n        <div class=\"right\">\r\n            <" +
                    "a href=\"http://www.neptuo.com\">Neptuo");
            this.Content.Add("</a>\r\n            <a href=\"http://te.neptuo.com\">TemplateEngine");
            this.Content.Add("</a>\r\n            © 2013\r\n        ");
            this.Content.Add("</div>\r\n        <div class=\"clear\">");
            this.Content.Add("</div>\r\n    ");
            this.Content.Add("</footer>\r\n\r\n    <script src=\"../../Design/Scripts/jquery-1.9.1.js\">");
            this.Content.Add("</script>\r\n    <script src=\"../../Design/Scripts/bootstrap.js\">");
            this.Content.Add("</script>\r\n");
            this.Content.Add("</body>\r\n");
            this.Content.Add("</html>\r\n");
        }
        private Neptuo.TemplateEngine.Web.Controls.DoctypeControl field82_Create()
        {
            Neptuo.TemplateEngine.Web.Controls.DoctypeControl field82 = new Neptuo.TemplateEngine.Web.Controls.DoctypeControl();
            this.componentManager.AddComponent(field82, this.field82_Bind);
            return field82;
        }
        private void field82_Bind(Neptuo.TemplateEngine.Web.Controls.DoctypeControl field82)
        {
            field82.Type = Neptuo.TemplateEngine.Web.Controls.DoctypeType.Xhtml;
        }
        private Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder field83_Create()
        {
            Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder field83 = new Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder(((Neptuo.TemplateEngine.Web.TemplateContentStorageStack)(this.dependencyProvider.Resolve(typeof(Neptuo.TemplateEngine.Web.TemplateContentStorageStack), null))));
            this.componentManager.AddComponent(field83, this.field83_Bind);
            return field83;
        }
        private void field83_Bind(Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder field83)
        {
            field83.Name = "Title";
        }
        private Neptuo.TemplateEngine.Web.Controls.LiteralControl field84_Create()
        {
            Neptuo.TemplateEngine.Web.Controls.LiteralControl field84 = new Neptuo.TemplateEngine.Web.Controls.LiteralControl(this.componentManager);
            this.componentManager.AddComponent(field84, this.field84_Bind);
            this.componentManager.AttachObserver(field84, this.field85_Create(), this.field85_Bind);
            return field84;
        }
        private Neptuo.TemplateEngine.Web.Observers.IsPlaceholderObserver field85_Create()
        {
            Neptuo.TemplateEngine.Web.Observers.IsPlaceholderObserver field85 = new Neptuo.TemplateEngine.Web.Observers.IsPlaceholderObserver(((Neptuo.TemplateEngine.Web.TemplateContentStorageStack)(this.dependencyProvider.Resolve(typeof(Neptuo.TemplateEngine.Web.TemplateContentStorageStack), null))));
            this.componentManager.AddComponent(field85, this.field85_Bind);
            return field85;
        }
        private void field85_Bind(Neptuo.TemplateEngine.Web.Observers.IsPlaceholderObserver field85)
        {
            field85.IsPlaceholder = "Title";
        }
        private void field84_Bind(Neptuo.TemplateEngine.Web.Controls.LiteralControl field84)
        {
            field84.Text = " - ";
        }
        private Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder field86_Create()
        {
            Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder field86 = new Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder(((Neptuo.TemplateEngine.Web.TemplateContentStorageStack)(this.dependencyProvider.Resolve(typeof(Neptuo.TemplateEngine.Web.TemplateContentStorageStack), null))));
            this.componentManager.AddComponent(field86, this.field86_Bind);
            return field86;
        }
        private void field86_Bind(Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder field86)
        {
            field86.Name = "Head";
        }
        private Neptuo.TemplateEngine.Web.Controls.GenericContentControl field87_Create()
        {
            Neptuo.TemplateEngine.Web.Controls.GenericContentControl field87 = new Neptuo.TemplateEngine.Web.Controls.GenericContentControl(this.componentManager);
            this.componentManager.AddComponent(field87, this.field87_Bind);
            return field87;
        }
        private void field87_Bind(Neptuo.TemplateEngine.Web.Controls.GenericContentControl field87)
        {
            field87.TagName = "a";
            field87.SetAttribute("class", "navbar-brand");
            field87.SetAttribute("href", this.ResolveUrl("~/Home.aspx"));
            field87.Content = new System.Collections.Generic.List<object>();
            field87.Content.Add("\r\n                <span class=\"glyphicon glyphicon-refresh\">");
            field87.Content.Add("</span>\r\n                TemplateEngine\r\n            ");
        }
        private Neptuo.TemplateEngine.Web.Controls.GenericContentControl field88_Create()
        {
            Neptuo.TemplateEngine.Web.Controls.GenericContentControl field88 = new Neptuo.TemplateEngine.Web.Controls.GenericContentControl(this.componentManager);
            this.componentManager.AddComponent(field88, this.field88_Bind);
            return field88;
        }
        private void field88_Bind(Neptuo.TemplateEngine.Web.Controls.GenericContentControl field88)
        {
            field88.TagName = "a";
            field88.SetAttribute("href", this.ResolveUrl("~/Home.aspx"));
            field88.Content = new System.Collections.Generic.List<object>();
            field88.Content.Add("\r\n                    ");
            field88.Content.Add(this.field89_Create());
            field88.Content.Add("\r\n                ");
        }
        private Neptuo.TemplateEngine.Web.Controls.LiteralControl field89_Create()
        {
            Neptuo.TemplateEngine.Web.Controls.LiteralControl field89 = new Neptuo.TemplateEngine.Web.Controls.LiteralControl(this.componentManager);
            this.componentManager.AddComponent(field89, this.field89_Bind);
            return field89;
        }
        private void field89_Bind(Neptuo.TemplateEngine.Web.Controls.LiteralControl field89)
        {
            field89.Text = Neptuo.TemplateEngine.Web.LocalizationHelper.Translate("Web");
        }
        private Neptuo.TemplateEngine.Web.Controls.GenericContentControl field90_Create()
        {
            Neptuo.TemplateEngine.Web.Controls.GenericContentControl field90 = new Neptuo.TemplateEngine.Web.Controls.GenericContentControl(this.componentManager);
            this.componentManager.AddComponent(field90, this.field90_Bind);
            return field90;
        }
        private void field90_Bind(Neptuo.TemplateEngine.Web.Controls.GenericContentControl field90)
        {
            field90.TagName = "a";
            field90.SetAttribute("href", this.ResolveUrl("~/Accounts/UserList.aspx"));
            field90.Content = new System.Collections.Generic.List<object>();
            field90.Content.Add("\r\n                    ");
            field90.Content.Add(this.field91_Create());
            field90.Content.Add("\r\n                ");
        }
        private Neptuo.TemplateEngine.Web.Controls.LiteralControl field91_Create()
        {
            Neptuo.TemplateEngine.Web.Controls.LiteralControl field91 = new Neptuo.TemplateEngine.Web.Controls.LiteralControl(this.componentManager);
            this.componentManager.AddComponent(field91, this.field91_Bind);
            return field91;
        }
        private void field91_Bind(Neptuo.TemplateEngine.Web.Controls.LiteralControl field91)
        {
            field91.Text = Neptuo.TemplateEngine.Web.LocalizationHelper.Translate("User accounts");
        }
        private Neptuo.TemplateEngine.Web.Controls.GenericContentControl field92_Create()
        {
            Neptuo.TemplateEngine.Web.Controls.GenericContentControl field92 = new Neptuo.TemplateEngine.Web.Controls.GenericContentControl(this.componentManager);
            this.componentManager.AddComponent(field92, this.field92_Bind);
            this.componentManager.AttachObserver(field92, this.field93_Create(), this.field93_Bind);
            return field92;
        }
        private Neptuo.TemplateEngine.Web.Observers.IsPlaceholderObserver field93_Create()
        {
            Neptuo.TemplateEngine.Web.Observers.IsPlaceholderObserver field93 = new Neptuo.TemplateEngine.Web.Observers.IsPlaceholderObserver(((Neptuo.TemplateEngine.Web.TemplateContentStorageStack)(this.dependencyProvider.Resolve(typeof(Neptuo.TemplateEngine.Web.TemplateContentStorageStack), null))));
            this.componentManager.AddComponent(field93, this.field93_Bind);
            return field93;
        }
        private void field93_Bind(Neptuo.TemplateEngine.Web.Observers.IsPlaceholderObserver field93)
        {
            field93.IsPlaceholder = "SideNav";
        }
        private void field92_Bind(Neptuo.TemplateEngine.Web.Controls.GenericContentControl field92)
        {
            field92.TagName = "div";
            field92.SetAttribute("class", "side-navbar");
            field92.Content = new System.Collections.Generic.List<object>();
            field92.Content.Add("\r\n            ");
            field92.Content.Add(this.field94_Create());
            field92.Content.Add("\r\n        ");
        }
        private Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder field94_Create()
        {
            Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder field94 = new Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder(((Neptuo.TemplateEngine.Web.TemplateContentStorageStack)(this.dependencyProvider.Resolve(typeof(Neptuo.TemplateEngine.Web.TemplateContentStorageStack), null))));
            this.componentManager.AddComponent(field94, this.field94_Bind);
            return field94;
        }
        private void field94_Bind(Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder field94)
        {
            field94.Name = "SideNav";
        }
        private Neptuo.TemplateEngine.Web.Controls.MessagePanelControl field95_Create()
        {
            Neptuo.TemplateEngine.Web.Controls.MessagePanelControl field95 = new Neptuo.TemplateEngine.Web.Controls.MessagePanelControl(this.componentManager, ((Neptuo.TemplateEngine.Web.MessageStorage)(this.dependencyProvider.Resolve(typeof(Neptuo.TemplateEngine.Web.MessageStorage), null))));
            this.componentManager.AddComponent(field95, this.field95_Bind);
            return field95;
        }
        private void field95_Bind(Neptuo.TemplateEngine.Web.Controls.MessagePanelControl field95)
        {
            field95.Key = "";
        }
        private Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder field96_Create()
        {
            Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder field96 = new Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder(((Neptuo.TemplateEngine.Web.TemplateContentStorageStack)(this.dependencyProvider.Resolve(typeof(Neptuo.TemplateEngine.Web.TemplateContentStorageStack), null))));
            this.componentManager.AddComponent(field96, this.field96_Bind);
            return field96;
        }
        private void field96_Bind(Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder field96)
        {
            field96.Name = "Body";
        }
    }
}
