/* Generated by SharpKit 5 v5.3.4 */
if (typeof($CreateDelegate)=='undefined'){
    if(typeof($iKey)=='undefined') var $iKey = 0;
    if(typeof($pKey)=='undefined') var $pKey = String.fromCharCode(1);
    var $CreateDelegate = function(target, func){
        if (target == null || func == null) 
            return func;
        if(func.target==target && func.func==func)
            return func;
        if (target.$delegateCache == null)
            target.$delegateCache = {};
        if (func.$key == null)
            func.$key = $pKey + String(++$iKey);
        var delegate;
        if(target.$delegateCache!=null)
            delegate = target.$delegateCache[func.$key];
        if (delegate == null){
            delegate = function(){
                return func.apply(target, arguments);
            };
            delegate.func = func;
            delegate.target = target;
            delegate.isDelegate = true;
            if(target.$delegateCache!=null)
                target.$delegateCache[func.$key] = delegate;
        }
        return delegate;
    }
}
if (typeof(JsTypes) == "undefined")
    var JsTypes = [];
var Neptuo$TemplateEngine$Web$Controls$ControlBase =
{
    fullname: "Neptuo.TemplateEngine.Web.Controls.ControlBase",
    baseTypeName: "System.Object",
    assemblyName: "Neptuo.TemplateEngine.Web.Client",
    interfaceNames: ["Neptuo.Templates.Controls.IControl"],
    Kind: "Class",
    definition:
    {
        ctor: function (componentManager)
        {
            this.defaultPropertyName = null;
            this._ComponentManager = null;
            System.Object.ctor.call(this);
            this.set_ComponentManager(componentManager);
        },
        ComponentManager$$: "Neptuo.Templates.IComponentManager",
        get_ComponentManager: function ()
        {
            return this._ComponentManager;
        },
        set_ComponentManager: function (value)
        {
            this._ComponentManager = value;
        },
        DefaultPropertyName$$: "System.String",
        get_DefaultPropertyName: function ()
        {
            if (this.defaultPropertyName == null)
            {
                var attr = Neptuo.Reflection.ReflectionHelper.GetAttribute$1(System.ComponentModel.DefaultPropertyAttribute.ctor, this.GetType());
                if (attr != null)
                    this.defaultPropertyName = attr.get_Name();
            }
            return this.defaultPropertyName;
        },
        set_DefaultPropertyName: function (value)
        {
            this.defaultPropertyName = value;
        },
        OnInit: function ()
        {
        },
        Render: function (writer)
        {
        },
        InitComponent: function (component)
        {
            this.get_ComponentManager().Init(component);
        },
        RenderComponent: function (component, writer)
        {
            this.get_ComponentManager().Render(component, writer);
        },
        InitComponents$1: function (T, compoments)
        {
            if (compoments != null)
            {
                var $it1 = compoments.GetEnumerator();
                while ($it1.MoveNext())
                {
                    var component = $it1.get_Current();
                    this.InitComponent(component);
                }
            }
        }
    },
    ctors: [ {name: "ctor", parameters: ["Neptuo.Templates.IComponentManager"]}],
    IsAbstract: true
};
JsTypes.push(Neptuo$TemplateEngine$Web$Controls$ControlBase);
var Neptuo$TemplateEngine$Web$Controls$FileTemplate2 =
{
    fullname: "Neptuo.TemplateEngine.Web.Controls.FileTemplate2",
    baseTypeName: "System.Object",
    assemblyName: "Neptuo.TemplateEngine.Web.Client",
    interfaceNames: ["Neptuo.TemplateEngine.Web.Controls.ITemplate"],
    Kind: "Class",
    definition:
    {
        ctor: function (dependencyProvider, componentManager)
        {
            this.dependencyProvider = null;
            this.componentManager = null;
            this._Path = null;
            System.Object.ctor.call(this);
            this.dependencyProvider = dependencyProvider;
            this.componentManager = componentManager;
        },
        Path$$: "System.String",
        get_Path: function ()
        {
            return this._Path;
        },
        set_Path: function (value)
        {
            this._Path = value;
        },
        CreateView: function ()
        {
            if (this.get_Path() == "~/Views/Shared/AdminLayout.view")
                return new Neptuo.Templates.View_B3FB932CB3BBED93A72876CB64C25B2BDE4D0C0E.ctor();
            return null;
        },
        CreateInstance: function ()
        {
            var view = this.CreateView();
            view.Setup(new Neptuo.Templates.BaseViewPage.ctor(this.componentManager), this.componentManager, this.dependencyProvider);
            view.CreateControls();
            var templateContent = new Neptuo.TemplateEngine.Web.Controls.ViewTemplateContent.ctor(view);
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.ViewTemplateContent.ctor, templateContent, null);
            return templateContent;
        },
        Dispose: function ()
        {
        }
    },
    ctors: [ {name: "ctor", parameters: ["Neptuo.IDependencyProvider", "Neptuo.Templates.IComponentManager"]}],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Web$Controls$FileTemplate2);
var Neptuo$TemplateEngine$Web$Controls$ITextControl = {fullname: "Neptuo.TemplateEngine.Web.Controls.ITextControl", baseTypeName: "System.Object", assemblyName: "Neptuo.TemplateEngine.Web.Client", Kind: "Interface", ctors: [], IsAbstract: true};
JsTypes.push(Neptuo$TemplateEngine$Web$Controls$ITextControl);
var Neptuo$TemplateEngine$Web$Controls$LiteralControl =
{
    fullname: "Neptuo.TemplateEngine.Web.Controls.LiteralControl",
    baseTypeName: "Neptuo.TemplateEngine.Web.Controls.ControlBase",
    assemblyName: "Neptuo.TemplateEngine.Web.Client",
    interfaceNames: ["Neptuo.TemplateEngine.Web.Controls.ITextControl"],
    Kind: "Class",
    definition:
    {
        ctor: function (componentManager)
        {
            this._Text = null;
            this._FormatString = null;
            Neptuo.TemplateEngine.Web.Controls.ControlBase.ctor.call(this, componentManager);
        },
        Text$$: "System.String",
        get_Text: function ()
        {
            return this._Text;
        },
        set_Text: function (value)
        {
            this._Text = value;
        },
        FormatString$$: "System.String",
        get_FormatString: function ()
        {
            return this._FormatString;
        },
        set_FormatString: function (value)
        {
            this._FormatString = value;
        },
        Render: function (writer)
        {
            if (!System.String.IsNullOrEmpty(this.get_FormatString()))
                writer.Content$$String(System.String.Format$$String$$Object(this.get_FormatString(), this.get_Text()));
            else
                writer.Content$$String(this.get_Text());
        }
    },
    ctors: [ {name: "ctor", parameters: ["Neptuo.Templates.IComponentManager"]}],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Web$Controls$LiteralControl);
var Neptuo$TemplateEngine$Web$Extensions$CurrentUrlExtension =
{
    fullname: "Neptuo.TemplateEngine.Web.Extensions.CurrentUrlExtension",
    baseTypeName: "System.Object",
    assemblyName: "Neptuo.TemplateEngine.Web.Client",
    interfaceNames: ["Neptuo.Templates.Extensions.IValueExtension"],
    Kind: "Class",
    definition:
    {
        ctor: function ()
        {
            System.Object.ctor.call(this);
        },
        ProvideValue: function (context)
        {
            return location.href;
        }
    },
    ctors: [ {name: "ctor", parameters: []}],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Web$Extensions$CurrentUrlExtension);
var Neptuo$TemplateEngine$Web$GeneratedViewBase =
{
    fullname: "Neptuo.TemplateEngine.Web.GeneratedViewBase",
    baseTypeName: "Neptuo.Templates.BaseGeneratedView",
    assemblyName: "Neptuo.TemplateEngine.Web.Client",
    Kind: "Class",
    definition:
    {
        ctor: function ()
        {
            this.urlProvider = null;
            Neptuo.Templates.BaseGeneratedView.ctor.call(this);
        },
        ResolveUrl: function (relativeUrl)
        {
            if (this.urlProvider == null)
                this.urlProvider = Neptuo.DependencyProviderExtensions.Resolve$1$$IDependencyProvider(Neptuo.Templates.IVirtualUrlProvider.ctor, this.dependencyProvider);
            return this.urlProvider.ResolveUrl(relativeUrl);
        },
        CastValueTo$1: function (T, value)
        {
            return Cast(value, T);
        }
    },
    ctors: [ {name: "ctor", parameters: []}],
    IsAbstract: true
};
JsTypes.push(Neptuo$TemplateEngine$Web$GeneratedViewBase);
var Neptuo$Templates$View_3D09FEDA526F72327E9894F4A68B10A6DDEF92A5 =
{
    fullname: "Neptuo.Templates.View_3D09FEDA526F72327E9894F4A68B10A6DDEF92A5",
    baseTypeName: "Neptuo.TemplateEngine.Web.GeneratedViewBase",
    assemblyName: "Neptuo.TemplateEngine.Web.Client",
    interfaceNames: ["System.IDisposable"],
    Kind: "Class",
    definition:
    {
        ctor: function ()
        {
            Neptuo.TemplateEngine.Web.GeneratedViewBase.ctor.call(this);
        },
        CreateViewPageControls: function (viewPage)
        {
            this.get_Content().Add("<strong>\r\n    ");
            this.get_Content().Add(this.field97_Create());
            this.get_Content().Add("\r\n");
            this.get_Content().Add("</strong>\r\n");
        },
        field97_Create: function ()
        {
            var field97 = new Neptuo.TemplateEngine.Web.Controls.LiteralControl.ctor(this.componentManager);
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.LiteralControl.ctor, field97, $CreateDelegate(this, this.field97_Bind));
            return field97;
        },
        field97_Bind: function (field97)
        {
            field97.set_Text("Hello [from login]!!");
        }
    },
    ctors: [ {name: "ctor", parameters: []}],
    IsAbstract: false
};
JsTypes.push(Neptuo$Templates$View_3D09FEDA526F72327E9894F4A68B10A6DDEF92A5);
var Neptuo$Templates$View_80DAA87AF7E7701DF7B03F434DCB9D17B7540026 =
{
    fullname: "Neptuo.Templates.View_80DAA87AF7E7701DF7B03F434DCB9D17B7540026",
    baseTypeName: "Neptuo.TemplateEngine.Web.GeneratedViewBase",
    assemblyName: "Neptuo.TemplateEngine.Web.Client",
    interfaceNames: ["System.IDisposable"],
    Kind: "Class",
    definition:
    {
        ctor: function ()
        {
            Neptuo.TemplateEngine.Web.GeneratedViewBase.ctor.call(this);
        },
        CreateViewPageControls: function (viewPage)
        {
            this.get_Content().Add(this.field1_Create());
        },
        field1_Create: function ()
        {
            var field1 = new Neptuo.TemplateEngine.Web.Controls.TemplateControl.ctor(this.componentManager, (Cast((this.dependencyProvider.Resolve(Typeof(Neptuo.TemplateEngine.Web.TemplateContentStorageStack.ctor), null)), Neptuo.TemplateEngine.Web.TemplateContentStorageStack.ctor)));
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.TemplateControl.ctor, field1, $CreateDelegate(this, this.field1_Bind));
            return field1;
        },
        field1_Bind: function (field1)
        {
            field1.set_Template(this.field2_Create());
            field1.set_Content(new System.Collections.Generic.List$1.ctor(Neptuo.TemplateEngine.Web.Controls.TemplateContentControl.ctor));
            field1.get_Content().Add(this.field3_Create());
            field1.get_Content().Add(this.field4_Create());
        },
        field2_Create: function ()
        {
            var field2 = new Neptuo.TemplateEngine.Web.Controls.FileTemplate2.ctor((Cast((this.dependencyProvider.Resolve(Typeof(Neptuo.IDependencyProvider.ctor), null)), Neptuo.IDependencyProvider.ctor)), (Cast((this.dependencyProvider.Resolve(Typeof(Neptuo.Templates.IComponentManager.ctor), null)), Neptuo.Templates.IComponentManager.ctor)));
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.FileTemplate2.ctor, field2, $CreateDelegate(this, this.field2_Bind));
            return field2;
        },
        field2_Bind: function (field2)
        {
            field2.set_Path("~/Views/Shared/AdminLayout.view");
        },
        field3_Create: function ()
        {
            var field3 = new Neptuo.TemplateEngine.Web.Controls.TemplateContentControl.ctor(this.componentManager);
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.TemplateContentControl.ctor, field3, $CreateDelegate(this, this.field3_Bind));
            return field3;
        },
        field3_Bind: function (field3)
        {
            field3.set_Name("Body");
            field3.set_Content(new System.Collections.Generic.List$1.ctor(System.Object.ctor));
            field3.get_Content().Add("\r\n\r\n        <h1>Welcome!");
            field3.get_Content().Add("</h1>\r\n\r\n    ");
        },
        field4_Create: function ()
        {
            var field4 = new Neptuo.TemplateEngine.Web.Controls.TemplateContentControl.ctor(this.componentManager);
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.TemplateContentControl.ctor, field4, $CreateDelegate(this, this.field4_Bind));
            return field4;
        },
        field4_Bind: function (field4)
        {
            field4.set_Name("Title");
            field4.set_Content(new System.Collections.Generic.List$1.ctor(System.Object.ctor));
            field4.get_Content().Add("Home");
        }
    },
    ctors: [ {name: "ctor", parameters: []}],
    IsAbstract: false
};
JsTypes.push(Neptuo$Templates$View_80DAA87AF7E7701DF7B03F434DCB9D17B7540026);
var Neptuo$Templates$View_B3FB932CB3BBED93A72876CB64C25B2BDE4D0C0E =
{
    fullname: "Neptuo.Templates.View_B3FB932CB3BBED93A72876CB64C25B2BDE4D0C0E",
    baseTypeName: "Neptuo.TemplateEngine.Web.GeneratedViewBase",
    assemblyName: "Neptuo.TemplateEngine.Web.Client",
    interfaceNames: ["System.IDisposable"],
    Kind: "Class",
    definition:
    {
        ctor: function ()
        {
            Neptuo.TemplateEngine.Web.GeneratedViewBase.ctor.call(this);
        },
        CreateViewPageControls: function (viewPage)
        {
            this.get_Content().Add(this.field82_Create());
            this.get_Content().Add("\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n    <meta charset=\"utf-8\" />\r\n    <title>\r\n        ");
            this.get_Content().Add(this.field83_Create());
            this.get_Content().Add("\r\n        ");
            this.get_Content().Add(this.field84_Create());
            this.get_Content().Add("\r\n        TemplateEngine\r\n    ");
            this.get_Content().Add("</title>\r\n    \r\n    <link href=\"../../Design/Styles/bootstrap.css\" rel=\"stylesheet\" />\r\n    <link href=\"../../Design/Styles/bootstrap-theme.css\" rel=\"stylesheet\" />\r\n    <link href=\"../../Design/Styles/My/Common.css\" rel=\"stylesheet\" />\r\n    <link href=\"../../Design/Styles/My/Layout.css\" rel=\"stylesheet\" />\r\n\r\n    ");
            this.get_Content().Add(this.field86_Create());
            this.get_Content().Add("\r\n\r\n");
            this.get_Content().Add("</head>\r\n<body>\r\n\r\n    <div class=\"navbar navbar-fixed-top navbar-main\">\r\n        <div class=\"navbar-header\">\r\n            ");
            this.get_Content().Add(this.field87_Create());
            this.get_Content().Add("\r\n        ");
            this.get_Content().Add("</div>\r\n        <ul class=\"nav navbar-nav\">\r\n            <li>\r\n                ");
            this.get_Content().Add(this.field88_Create());
            this.get_Content().Add("\r\n            ");
            this.get_Content().Add("</li>\r\n            <li>\r\n                ");
            this.get_Content().Add(this.field90_Create());
            this.get_Content().Add("\r\n            ");
            this.get_Content().Add("</li>\r\n        ");
            this.get_Content().Add("</ul>\r\n    ");
            this.get_Content().Add("</div>\r\n\r\n    <div class=\"body-container\">\r\n        ");
            this.get_Content().Add(this.field92_Create());
            this.get_Content().Add("\r\n        <div class=\"body\">\r\n            ");
            this.get_Content().Add(this.field95_Create());
            this.get_Content().Add("\r\n            ");
            this.get_Content().Add(this.field96_Create());
            this.get_Content().Add("\r\n        ");
            this.get_Content().Add("</div>\r\n    ");
            this.get_Content().Add("</div>\r\n\r\n    <footer class=\"navbar\">\r\n        <div class=\"right\">\r\n            <a href=\"http://www.neptuo.com\">Neptuo");
            this.get_Content().Add("</a>\r\n            <a href=\"http://te.neptuo.com\">TemplateEngine");
            this.get_Content().Add("</a>\r\n            © 2013\r\n        ");
            this.get_Content().Add("</div>\r\n        <div class=\"clear\">");
            this.get_Content().Add("</div>\r\n    ");
            this.get_Content().Add("</footer>\r\n\r\n    <script src=\"../../Design/Scripts/jquery-1.9.1.js\">");
            this.get_Content().Add("</script>\r\n    <script src=\"../../Design/Scripts/bootstrap.js\">");
            this.get_Content().Add("</script>\r\n");
            this.get_Content().Add("</body>\r\n");
            this.get_Content().Add("</html>\r\n");
        },
        field82_Create: function ()
        {
            var field82 = new Neptuo.TemplateEngine.Web.Controls.DoctypeControl.ctor();
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.DoctypeControl.ctor, field82, $CreateDelegate(this, this.field82_Bind));
            return field82;
        },
        field82_Bind: function (field82)
        {
            field82.set_Type(1);
        },
        field83_Create: function ()
        {
            var field83 = new Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder.ctor((Cast((this.dependencyProvider.Resolve(Typeof(Neptuo.TemplateEngine.Web.TemplateContentStorageStack.ctor), null)), Neptuo.TemplateEngine.Web.TemplateContentStorageStack.ctor)));
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder.ctor, field83, $CreateDelegate(this, this.field83_Bind));
            return field83;
        },
        field83_Bind: function (field83)
        {
            field83.set_Name("Title");
        },
        field84_Create: function ()
        {
            var field84 = new Neptuo.TemplateEngine.Web.Controls.LiteralControl.ctor(this.componentManager);
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.LiteralControl.ctor, field84, $CreateDelegate(this, this.field84_Bind));
            this.componentManager.AttachObserver$1(Neptuo.TemplateEngine.Web.Observers.IsPlaceholderObserver.ctor, field84, this.field85_Create(), $CreateDelegate(this, this.field85_Bind));
            return field84;
        },
        field85_Create: function ()
        {
            var field85 = new Neptuo.TemplateEngine.Web.Observers.IsPlaceholderObserver.ctor((Cast((this.dependencyProvider.Resolve(Typeof(Neptuo.TemplateEngine.Web.TemplateContentStorageStack.ctor), null)), Neptuo.TemplateEngine.Web.TemplateContentStorageStack.ctor)));
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Observers.IsPlaceholderObserver.ctor, field85, $CreateDelegate(this, this.field85_Bind));
            return field85;
        },
        field85_Bind: function (field85)
        {
            field85.set_IsPlaceholder("Title");
        },
        field84_Bind: function (field84)
        {
            field84.set_Text(" - ");
        },
        field86_Create: function ()
        {
            var field86 = new Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder.ctor((Cast((this.dependencyProvider.Resolve(Typeof(Neptuo.TemplateEngine.Web.TemplateContentStorageStack.ctor), null)), Neptuo.TemplateEngine.Web.TemplateContentStorageStack.ctor)));
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder.ctor, field86, $CreateDelegate(this, this.field86_Bind));
            return field86;
        },
        field86_Bind: function (field86)
        {
            field86.set_Name("Head");
        },
        field87_Create: function ()
        {
            var field87 = new Neptuo.TemplateEngine.Web.Controls.GenericContentControl.ctor(this.componentManager);
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.GenericContentControl.ctor, field87, $CreateDelegate(this, this.field87_Bind));
            return field87;
        },
        field87_Bind: function (field87)
        {
            field87.set_TagName("a");
            field87.SetAttribute("class", "navbar-brand");
            field87.SetAttribute("href", this.ResolveUrl("~/Home.aspx"));
            field87.set_Content(new System.Collections.Generic.List$1.ctor(System.Object.ctor));
            field87.get_Content().Add("\r\n                <span class=\"glyphicon glyphicon-refresh\">");
            field87.get_Content().Add("</span>\r\n                TemplateEngine\r\n            ");
        },
        field88_Create: function ()
        {
            var field88 = new Neptuo.TemplateEngine.Web.Controls.GenericContentControl.ctor(this.componentManager);
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.GenericContentControl.ctor, field88, $CreateDelegate(this, this.field88_Bind));
            return field88;
        },
        field88_Bind: function (field88)
        {
            field88.set_TagName("a");
            field88.SetAttribute("href", this.ResolveUrl("~/Home.aspx"));
            field88.set_Content(new System.Collections.Generic.List$1.ctor(System.Object.ctor));
            field88.get_Content().Add("\r\n                    ");
            field88.get_Content().Add(this.field89_Create());
            field88.get_Content().Add("\r\n                ");
        },
        field89_Create: function ()
        {
            var field89 = new Neptuo.TemplateEngine.Web.Controls.LiteralControl.ctor(this.componentManager);
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.LiteralControl.ctor, field89, $CreateDelegate(this, this.field89_Bind));
            return field89;
        },
        field89_Bind: function (field89)
        {
            field89.set_Text(Neptuo.TemplateEngine.Web.LocalizationHelper.Translate("Web"));
        },
        field90_Create: function ()
        {
            var field90 = new Neptuo.TemplateEngine.Web.Controls.GenericContentControl.ctor(this.componentManager);
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.GenericContentControl.ctor, field90, $CreateDelegate(this, this.field90_Bind));
            return field90;
        },
        field90_Bind: function (field90)
        {
            field90.set_TagName("a");
            field90.SetAttribute("href", this.ResolveUrl("~/Accounts/UserList.aspx"));
            field90.set_Content(new System.Collections.Generic.List$1.ctor(System.Object.ctor));
            field90.get_Content().Add("\r\n                    ");
            field90.get_Content().Add(this.field91_Create());
            field90.get_Content().Add("\r\n                ");
        },
        field91_Create: function ()
        {
            var field91 = new Neptuo.TemplateEngine.Web.Controls.LiteralControl.ctor(this.componentManager);
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.LiteralControl.ctor, field91, $CreateDelegate(this, this.field91_Bind));
            return field91;
        },
        field91_Bind: function (field91)
        {
            field91.set_Text(Neptuo.TemplateEngine.Web.LocalizationHelper.Translate("User accounts"));
        },
        field92_Create: function ()
        {
            var field92 = new Neptuo.TemplateEngine.Web.Controls.GenericContentControl.ctor(this.componentManager);
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.GenericContentControl.ctor, field92, $CreateDelegate(this, this.field92_Bind));
            this.componentManager.AttachObserver$1(Neptuo.TemplateEngine.Web.Observers.IsPlaceholderObserver.ctor, field92, this.field93_Create(), $CreateDelegate(this, this.field93_Bind));
            return field92;
        },
        field93_Create: function ()
        {
            var field93 = new Neptuo.TemplateEngine.Web.Observers.IsPlaceholderObserver.ctor((Cast((this.dependencyProvider.Resolve(Typeof(Neptuo.TemplateEngine.Web.TemplateContentStorageStack.ctor), null)), Neptuo.TemplateEngine.Web.TemplateContentStorageStack.ctor)));
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Observers.IsPlaceholderObserver.ctor, field93, $CreateDelegate(this, this.field93_Bind));
            return field93;
        },
        field93_Bind: function (field93)
        {
            field93.set_IsPlaceholder("SideNav");
        },
        field92_Bind: function (field92)
        {
            field92.set_TagName("div");
            field92.SetAttribute("class", "side-navbar");
            field92.set_Content(new System.Collections.Generic.List$1.ctor(System.Object.ctor));
            field92.get_Content().Add("\r\n            ");
            field92.get_Content().Add(this.field94_Create());
            field92.get_Content().Add("\r\n        ");
        },
        field94_Create: function ()
        {
            var field94 = new Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder.ctor((Cast((this.dependencyProvider.Resolve(Typeof(Neptuo.TemplateEngine.Web.TemplateContentStorageStack.ctor), null)), Neptuo.TemplateEngine.Web.TemplateContentStorageStack.ctor)));
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder.ctor, field94, $CreateDelegate(this, this.field94_Bind));
            return field94;
        },
        field94_Bind: function (field94)
        {
            field94.set_Name("SideNav");
        },
        field95_Create: function ()
        {
            var field95 = new Neptuo.TemplateEngine.Web.Controls.MessagePanelControl.ctor(this.componentManager, (Cast((this.dependencyProvider.Resolve(Typeof(Neptuo.TemplateEngine.Web.MessageStorage.ctor), null)), Neptuo.TemplateEngine.Web.MessageStorage.ctor)));
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.MessagePanelControl.ctor, field95, $CreateDelegate(this, this.field95_Bind));
            return field95;
        },
        field95_Bind: function (field95)
        {
            field95.set_Key("");
        },
        field96_Create: function ()
        {
            var field96 = new Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder.ctor((Cast((this.dependencyProvider.Resolve(Typeof(Neptuo.TemplateEngine.Web.TemplateContentStorageStack.ctor), null)), Neptuo.TemplateEngine.Web.TemplateContentStorageStack.ctor)));
            this.componentManager.AddComponent$1(Neptuo.TemplateEngine.Web.Controls.TemplatePlaceholder.ctor, field96, $CreateDelegate(this, this.field96_Bind));
            return field96;
        },
        field96_Bind: function (field96)
        {
            field96.set_Name("Body");
        }
    },
    ctors: [ {name: "ctor", parameters: []}],
    IsAbstract: false
};
JsTypes.push(Neptuo$Templates$View_B3FB932CB3BBED93A72876CB64C25B2BDE4D0C0E);
