//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neptuo.Templates
{
    
    public sealed class View_3D09FEDA526F72327E9894F4A68B10A6DDEF92A5 : Neptuo.TemplateEngine.Web.GeneratedViewBase, System.IDisposable
    {
        protected override void CreateViewPageControls(Neptuo.Templates.IViewPage viewPage)
        {
            this.Content.Add("<strong>\r\n    ");
            this.Content.Add(this.field97_Create());
            this.Content.Add("\r\n");
            this.Content.Add("</strong>\r\n");
        }
        private Neptuo.TemplateEngine.Web.Controls.LiteralControl field97_Create()
        {
            Neptuo.TemplateEngine.Web.Controls.LiteralControl field97 = new Neptuo.TemplateEngine.Web.Controls.LiteralControl(this.componentManager);
            this.componentManager.AddComponent(field97, this.field97_Bind);
            return field97;
        }
        private void field97_Bind(Neptuo.TemplateEngine.Web.Controls.LiteralControl field97)
        {
            field97.Text = "Hello [from login]!!";
        }
    }
}
