//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neptuo.Templates
{
    
    public sealed class View_80DAA87AF7E7701DF7B03F434DCB9D17B7540026 : Neptuo.TemplateEngine.Web.GeneratedViewBase, System.IDisposable
    {
        protected override void CreateViewPageControls(Neptuo.Templates.IViewPage viewPage)
        {
            this.Content.Add(this.field1_Create());
        }
        private Neptuo.TemplateEngine.Web.Controls.TemplateControl field1_Create()
        {
            Neptuo.TemplateEngine.Web.Controls.TemplateControl field1 = new Neptuo.TemplateEngine.Web.Controls.TemplateControl(this.componentManager, ((Neptuo.TemplateEngine.Web.TemplateContentStorageStack)(this.dependencyProvider.Resolve(typeof(Neptuo.TemplateEngine.Web.TemplateContentStorageStack), null))));
            this.componentManager.AddComponent(field1, this.field1_Bind);
            return field1;
        }
        private void field1_Bind(Neptuo.TemplateEngine.Web.Controls.TemplateControl field1)
        {
            field1.Template = this.field2_Create();
            field1.Content = new System.Collections.Generic.List<Neptuo.TemplateEngine.Web.Controls.TemplateContentControl>();
            field1.Content.Add(this.field3_Create());
            field1.Content.Add(this.field4_Create());
        }
        private Neptuo.TemplateEngine.Web.Controls.FileTemplate2 field2_Create()
        {
            Neptuo.TemplateEngine.Web.Controls.FileTemplate2 field2 = new Neptuo.TemplateEngine.Web.Controls.FileTemplate2(((Neptuo.IDependencyProvider)(this.dependencyProvider.Resolve(typeof(Neptuo.IDependencyProvider), null))), ((Neptuo.Templates.IComponentManager)(this.dependencyProvider.Resolve(typeof(Neptuo.Templates.IComponentManager), null))));
            this.componentManager.AddComponent(field2, this.field2_Bind);
            return field2;
        }
        private void field2_Bind(Neptuo.TemplateEngine.Web.Controls.FileTemplate2 field2)
        {
            field2.Path = "~/Views/Shared/AdminLayout.view";
        }
        private Neptuo.TemplateEngine.Web.Controls.TemplateContentControl field3_Create()
        {
            Neptuo.TemplateEngine.Web.Controls.TemplateContentControl field3 = new Neptuo.TemplateEngine.Web.Controls.TemplateContentControl(this.componentManager);
            this.componentManager.AddComponent(field3, this.field3_Bind);
            return field3;
        }
        private void field3_Bind(Neptuo.TemplateEngine.Web.Controls.TemplateContentControl field3)
        {
            field3.Name = "Body";
            field3.Content = new System.Collections.Generic.List<object>();
            field3.Content.Add("\r\n\r\n        <h1>Welcome!");
            field3.Content.Add("</h1>\r\n\r\n    ");
        }
        private Neptuo.TemplateEngine.Web.Controls.TemplateContentControl field4_Create()
        {
            Neptuo.TemplateEngine.Web.Controls.TemplateContentControl field4 = new Neptuo.TemplateEngine.Web.Controls.TemplateContentControl(this.componentManager);
            this.componentManager.AddComponent(field4, this.field4_Bind);
            return field4;
        }
        private void field4_Bind(Neptuo.TemplateEngine.Web.Controls.TemplateContentControl field4)
        {
            field4.Name = "Title";
            field4.Content = new System.Collections.Generic.List<object>();
            field4.Content.Add("Home");
        }
    }
}
