/* Generated by SharpKit 5 v5.4.4 */

if (typeof(JsTypes) == "undefined")
    var JsTypes = [];
var Neptuo$TemplateEngine$Publishing$ArticleLineEditViewModelConverter = {
    fullname: "Neptuo.TemplateEngine.Publishing.ArticleLineEditViewModelConverter",
    baseTypeName: "Neptuo.ComponentModel.Converters.ConverterBase$2",
    assemblyName: "Neptuo.TemplateEngine.Publishing.Client",
    Kind: "Class",
    definition: {
        ctor: function (){
            Neptuo.ComponentModel.Converters.ConverterBase$2.ctor.call(this, Object, Neptuo.TemplateEngine.Publishing.ViewModels.ArticleLineEditViewModel.ctor);
        },
        TryConvert: function (sourceValue, targetValue){
            targetValue.Value = new Neptuo.TemplateEngine.Publishing.ViewModels.ArticleLineEditViewModel.ctor();
            targetValue.Value.set_Key(sourceValue["Key"]);
            targetValue.Value.set_Name(sourceValue["Name"]);
            targetValue.Value.set_UrlPart(sourceValue["UrlPart"]);
            targetValue.Value.set_AvailableTagKeys(new System.Collections.Generic.List$1.ctor$$IEnumerable$1(System.Int32.ctor, sourceValue["AvailableTagKeys"]));
            return true;
        }
    },
    ctors: [{
        name: "ctor",
        parameters: []
    }
    ],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Publishing$ArticleLineEditViewModelConverter);
var Neptuo$TemplateEngine$Publishing$ArticleTagListResultConverter = {
    fullname: "Neptuo.TemplateEngine.Publishing.ArticleTagListResultConverter",
    baseTypeName: "Neptuo.TemplateEngine.ListResultConverterBase$2",
    assemblyName: "Neptuo.TemplateEngine.Publishing.Client",
    Kind: "Class",
    definition: {
        ctor: function (){
            Neptuo.TemplateEngine.ListResultConverterBase$2.ctor.call(this, Neptuo.TemplateEngine.Publishing.ArticleTagListResult.ctor, Neptuo.TemplateEngine.Publishing.ViewModels.ArticleTagViewModel.ctor);
        },
        TryConvertItem: function (sourceValue, item){
            return Neptuo.Converts.Try$2$$TSource$$TTarget(Object, Neptuo.TemplateEngine.Publishing.ViewModels.ArticleTagViewModel.ctor, sourceValue, item);
        },
        CreateResult: function (data, totalCount){
            return new Neptuo.TemplateEngine.Publishing.ArticleTagListResult.ctor(data, totalCount);
        }
    },
    ctors: [{
        name: "ctor",
        parameters: []
    }
    ],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Publishing$ArticleTagListResultConverter);
var Neptuo$TemplateEngine$Publishing$ArticleListResult = {
    fullname: "Neptuo.TemplateEngine.Publishing.ArticleListResult",
    baseTypeName: "Neptuo.TemplateEngine.Templates.DataSources.ListResult",
    assemblyName: "Neptuo.TemplateEngine.Publishing.Client",
    Kind: "Class",
    definition: {
        ctor: function (data, totalCount){
            Neptuo.TemplateEngine.Templates.DataSources.ListResult.ctor.call(this, data, totalCount);
        }
    },
    ctors: [{
        name: "ctor",
        parameters: ["System.Collections.IEnumerable", "System.Int32"]
    }
    ],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Publishing$ArticleListResult);
var Neptuo$TemplateEngine$Publishing$ArticleLineViewModelConverter = {
    fullname: "Neptuo.TemplateEngine.Publishing.ArticleLineViewModelConverter",
    baseTypeName: "Neptuo.ComponentModel.Converters.ConverterBase$2",
    assemblyName: "Neptuo.TemplateEngine.Publishing.Client",
    Kind: "Class",
    definition: {
        ctor: function (){
            Neptuo.ComponentModel.Converters.ConverterBase$2.ctor.call(this, Object, Neptuo.TemplateEngine.Publishing.ViewModels.ArticleLineViewModel.ctor);
        },
        TryConvert: function (sourceValue, targetValue){
            targetValue.Value = new Neptuo.TemplateEngine.Publishing.ViewModels.ArticleLineViewModel.ctor();
            targetValue.Value.set_Key(sourceValue["Key"]);
            targetValue.Value.set_Name(sourceValue["Name"]);
            targetValue.Value.set_UrlPart(sourceValue["UrlPart"]);
            return true;
        }
    },
    ctors: [{
        name: "ctor",
        parameters: []
    }
    ],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Publishing$ArticleLineViewModelConverter);
var Neptuo$TemplateEngine$Publishing$ArticleLineListResultConverter = {
    fullname: "Neptuo.TemplateEngine.Publishing.ArticleLineListResultConverter",
    baseTypeName: "Neptuo.TemplateEngine.ListResultConverterBase$2",
    assemblyName: "Neptuo.TemplateEngine.Publishing.Client",
    Kind: "Class",
    definition: {
        ctor: function (){
            Neptuo.TemplateEngine.ListResultConverterBase$2.ctor.call(this, Neptuo.TemplateEngine.Publishing.ArticleLineListResult.ctor, Neptuo.TemplateEngine.Publishing.ViewModels.ArticleLineViewModel.ctor);
        },
        TryConvertItem: function (sourceValue, item){
            return Neptuo.Converts.Try$2$$TSource$$TTarget(Object, Neptuo.TemplateEngine.Publishing.ViewModels.ArticleLineViewModel.ctor, sourceValue, item);
        },
        CreateResult: function (data, totalCount){
            return new Neptuo.TemplateEngine.Publishing.ArticleLineListResult.ctor(data, totalCount);
        }
    },
    ctors: [{
        name: "ctor",
        parameters: []
    }
    ],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Publishing$ArticleLineListResultConverter);
var Neptuo$TemplateEngine$Publishing$ArticleListResultConverter = {
    fullname: "Neptuo.TemplateEngine.Publishing.ArticleListResultConverter",
    baseTypeName: "Neptuo.TemplateEngine.ListResultConverterBase$2",
    assemblyName: "Neptuo.TemplateEngine.Publishing.Client",
    Kind: "Class",
    definition: {
        ctor: function (){
            Neptuo.TemplateEngine.ListResultConverterBase$2.ctor.call(this, Neptuo.TemplateEngine.Publishing.ArticleListResult.ctor, Neptuo.TemplateEngine.Publishing.ViewModels.ArticleViewModel.ctor);
        },
        TryConvertItem: function (sourceValue, item){
            return Neptuo.Converts.Try$2$$TSource$$TTarget(Object, Neptuo.TemplateEngine.Publishing.ViewModels.ArticleViewModel.ctor, sourceValue, item);
        },
        CreateResult: function (data, totalCount){
            return new Neptuo.TemplateEngine.Publishing.ArticleListResult.ctor(data, totalCount);
        }
    },
    ctors: [{
        name: "ctor",
        parameters: []
    }
    ],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Publishing$ArticleListResultConverter);
var Neptuo$TemplateEngine$Publishing$ArticleTagEditViewModelConverter = {
    fullname: "Neptuo.TemplateEngine.Publishing.ArticleTagEditViewModelConverter",
    baseTypeName: "Neptuo.ComponentModel.Converters.ConverterBase$2",
    assemblyName: "Neptuo.TemplateEngine.Publishing.Client",
    Kind: "Class",
    definition: {
        ctor: function (){
            Neptuo.ComponentModel.Converters.ConverterBase$2.ctor.call(this, Object, Neptuo.TemplateEngine.Publishing.ViewModels.ArticleTagEditViewModel.ctor);
        },
        TryConvert: function (sourceValue, targetValue){
            targetValue.Value = new Neptuo.TemplateEngine.Publishing.ViewModels.ArticleTagEditViewModel.ctor();
            targetValue.Value.set_Key(sourceValue["Key"]);
            targetValue.Value.set_Name(sourceValue["Name"]);
            targetValue.Value.set_UrlPart(sourceValue["UrlPart"]);
            return true;
        }
    },
    ctors: [{
        name: "ctor",
        parameters: []
    }
    ],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Publishing$ArticleTagEditViewModelConverter);
var Neptuo$TemplateEngine$Publishing$ArticleLineListResult = {
    fullname: "Neptuo.TemplateEngine.Publishing.ArticleLineListResult",
    baseTypeName: "Neptuo.TemplateEngine.Templates.DataSources.ListResult",
    assemblyName: "Neptuo.TemplateEngine.Publishing.Client",
    Kind: "Class",
    definition: {
        ctor: function (data, totalCount){
            Neptuo.TemplateEngine.Templates.DataSources.ListResult.ctor.call(this, data, totalCount);
        }
    },
    ctors: [{
        name: "ctor",
        parameters: ["System.Collections.IEnumerable", "System.Int32"]
    }
    ],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Publishing$ArticleLineListResult);
var Neptuo$TemplateEngine$Publishing$ArticleTagListResult = {
    fullname: "Neptuo.TemplateEngine.Publishing.ArticleTagListResult",
    baseTypeName: "Neptuo.TemplateEngine.Templates.DataSources.ListResult",
    assemblyName: "Neptuo.TemplateEngine.Publishing.Client",
    Kind: "Class",
    definition: {
        ctor: function (data, totalCount){
            Neptuo.TemplateEngine.Templates.DataSources.ListResult.ctor.call(this, data, totalCount);
        }
    },
    ctors: [{
        name: "ctor",
        parameters: ["System.Collections.IEnumerable", "System.Int32"]
    }
    ],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Publishing$ArticleTagListResult);
var Neptuo$TemplateEngine$Publishing$ArticleTagViewModelConverter = {
    fullname: "Neptuo.TemplateEngine.Publishing.ArticleTagViewModelConverter",
    baseTypeName: "Neptuo.ComponentModel.Converters.ConverterBase$2",
    assemblyName: "Neptuo.TemplateEngine.Publishing.Client",
    Kind: "Class",
    definition: {
        ctor: function (){
            Neptuo.ComponentModel.Converters.ConverterBase$2.ctor.call(this, Object, Neptuo.TemplateEngine.Publishing.ViewModels.ArticleTagViewModel.ctor);
        },
        TryConvert: function (sourceValue, targetValue){
            targetValue.Value = new Neptuo.TemplateEngine.Publishing.ViewModels.ArticleTagViewModel.ctor();
            targetValue.Value.set_Key(sourceValue["Key"]);
            targetValue.Value.set_Name(sourceValue["Name"]);
            targetValue.Value.set_UrlPart(sourceValue["UrlPart"]);
            return true;
        }
    },
    ctors: [{
        name: "ctor",
        parameters: []
    }
    ],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Publishing$ArticleTagViewModelConverter);
var Neptuo$TemplateEngine$Publishing$ArticleEditViewModelConverter = {
    fullname: "Neptuo.TemplateEngine.Publishing.ArticleEditViewModelConverter",
    baseTypeName: "Neptuo.ComponentModel.Converters.ConverterBase$2",
    assemblyName: "Neptuo.TemplateEngine.Publishing.Client",
    Kind: "Class",
    definition: {
        ctor: function (){
            Neptuo.ComponentModel.Converters.ConverterBase$2.ctor.call(this, Object, Neptuo.TemplateEngine.Publishing.ViewModels.ArticleEditViewModel.ctor);
        },
        TryConvert: function (sourceValue, targetValue){
            targetValue.Value = new Neptuo.TemplateEngine.Publishing.ViewModels.ArticleEditViewModel.ctor();
            targetValue.Value.set_Key(sourceValue["Key"]);
            targetValue.Value.set_Title(sourceValue["Title"]);
            targetValue.Value.set_UrlPart(sourceValue["UrlPart"]);
            targetValue.Value.set_Content(sourceValue["Content"]);
            targetValue.Value.set_IsVisible(sourceValue["IsVisible"]);
            targetValue.Value.set_Author(sourceValue["Author"]);
            targetValue.Value.set_LineKey(sourceValue["LineKey"]);
            targetValue.Value.set_TagKeys(new System.Collections.Generic.List$1.ctor$$IEnumerable$1(System.Int32.ctor, sourceValue["TagKeys"]));
            return true;
        }
    },
    ctors: [{
        name: "ctor",
        parameters: []
    }
    ],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Publishing$ArticleEditViewModelConverter);
var Neptuo$TemplateEngine$Publishing$ArticleViewModelConverter = {
    fullname: "Neptuo.TemplateEngine.Publishing.ArticleViewModelConverter",
    baseTypeName: "Neptuo.ComponentModel.Converters.ConverterBase$2",
    assemblyName: "Neptuo.TemplateEngine.Publishing.Client",
    Kind: "Class",
    definition: {
        ctor: function (){
            Neptuo.ComponentModel.Converters.ConverterBase$2.ctor.call(this, Object, Neptuo.TemplateEngine.Publishing.ViewModels.ArticleViewModel.ctor);
        },
        TryConvert: function (sourceValue, targetValue){
            targetValue.Value = new Neptuo.TemplateEngine.Publishing.ViewModels.ArticleViewModel.ctor();
            targetValue.Value.set_Key(sourceValue["Key"]);
            targetValue.Value.set_Title(sourceValue["Title"]);
            targetValue.Value.set_UrlPart(sourceValue["UrlPart"]);
            targetValue.Value.set_Content(sourceValue["Content"]);
            targetValue.Value.set_IsVisible(sourceValue["IsVisible"]);
            targetValue.Value.set_Author(sourceValue["Author"]);
            targetValue.Value.set_Created(sourceValue["Created"]);
            targetValue.Value.set_LastModified(sourceValue["LastModified"]);
            var lineValue = sourceValue["Line"];
            var line;
            if ((function (){
                var $1 = {
                    Value: line
                };
                var $res = Neptuo.Converts.Try$2$$TSource$$TTarget(Object, Neptuo.TemplateEngine.Publishing.ViewModels.ArticleLineViewModel.ctor, lineValue, $1);
                line = $1.Value;
                return $res;
            }).call(this))
                targetValue.Value.set_Line(line);
            var tags = new System.Collections.Generic.List$1.ctor(Neptuo.TemplateEngine.Publishing.ViewModels.ArticleTagViewModel.ctor);
            var tagsValue = sourceValue["Tags"];
            for (var i = 0; i < tagsValue.length; i++){
                var tagValue = tagsValue[i];
                var tag;
                if ((function (){
                    var $1 = {
                        Value: tag
                    };
                    var $res = Neptuo.Converts.Try$2$$TSource$$TTarget(Object, Neptuo.TemplateEngine.Publishing.ViewModels.ArticleTagViewModel.ctor, tagValue, $1);
                    tag = $1.Value;
                    return $res;
                }).call(this))
                    tags.Add(tag);
            }
            targetValue.Value.set_Tags(tags);
            return true;
        }
    },
    ctors: [{
        name: "ctor",
        parameters: []
    }
    ],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Publishing$ArticleViewModelConverter);
var Neptuo$TemplateEngine$Publishing$Bootstrap$PublishingBootstrapTask = {
    fullname: "Neptuo.TemplateEngine.Publishing.Bootstrap.PublishingBootstrapTask",
    baseTypeName: "System.Object",
    assemblyName: "Neptuo.TemplateEngine.Publishing.Client",
    interfaceNames: ["Neptuo.Bootstrap.IBootstrapTask"],
    Kind: "Class",
    definition: {
        ctor: function (){
            this.converterRepository = null;
            System.Object.ctor.call(this);
            this.converterRepository = Neptuo.Converts.get_Repository();
        },
        Initialize: function (){
            this.converterRepository.Add(Typeof(Object), Typeof(Neptuo.TemplateEngine.Publishing.ViewModels.ArticleViewModel.ctor), new Neptuo.TemplateEngine.Publishing.ArticleViewModelConverter.ctor()).Add(Typeof(Object), Typeof(Neptuo.TemplateEngine.Publishing.ViewModels.ArticleTagViewModel.ctor), new Neptuo.TemplateEngine.Publishing.ArticleTagViewModelConverter.ctor()).Add(Typeof(Object), Typeof(Neptuo.TemplateEngine.Publishing.ViewModels.ArticleLineViewModel.ctor), new Neptuo.TemplateEngine.Publishing.ArticleLineViewModelConverter.ctor()).Add(Typeof(Object), Typeof(Neptuo.TemplateEngine.Publishing.ArticleListResult.ctor), new Neptuo.TemplateEngine.Publishing.ArticleListResultConverter.ctor()).Add(Typeof(Object), Typeof(Neptuo.TemplateEngine.Publishing.ArticleTagListResult.ctor), new Neptuo.TemplateEngine.Publishing.ArticleTagListResultConverter.ctor()).Add(Typeof(Object), Typeof(Neptuo.TemplateEngine.Publishing.ArticleLineListResult.ctor), new Neptuo.TemplateEngine.Publishing.ArticleLineListResultConverter.ctor()).Add(Typeof(Object), Typeof(Neptuo.TemplateEngine.Publishing.ViewModels.ArticleEditViewModel.ctor), new Neptuo.TemplateEngine.Publishing.ArticleEditViewModelConverter.ctor()).Add(Typeof(Object), Typeof(Neptuo.TemplateEngine.Publishing.ViewModels.ArticleTagEditViewModel.ctor), new Neptuo.TemplateEngine.Publishing.ArticleTagEditViewModelConverter.ctor()).Add(Typeof(Object), Typeof(Neptuo.TemplateEngine.Publishing.ViewModels.ArticleLineEditViewModel.ctor), new Neptuo.TemplateEngine.Publishing.ArticleLineEditViewModelConverter.ctor());
        }
    },
    ctors: [{
        name: "ctor",
        parameters: []
    }
    ],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Publishing$Bootstrap$PublishingBootstrapTask);
var Neptuo$TemplateEngine$Publishing$Templates$DataSources$ArticleTagDataSource = {
    fullname: "Neptuo.TemplateEngine.Publishing.Templates.DataSources.ArticleTagDataSource",
    baseTypeName: "Neptuo.TemplateEngine.Templates.DataSources.FullDataSourceProxy$2",
    staticDefinition: {
        GetFilterListProperties: function (){
            return (function (){
                var $v1 = new System.Collections.Generic.List$1.ctor(System.String.ctor);
                $v1.Add("Key");
                $v1.Add("Name");
                $v1.Add("UrlPart");
                return $v1;
            })();
        },
        GetFilterSingleProperties: function (){
            return (function (){
                var $v2 = new System.Collections.Generic.List$1.ctor(System.String.ctor);
                $v2.Add("Key");
                return $v2;
            })();
        }
    },
    assemblyName: "Neptuo.TemplateEngine.Publishing.Client",
    interfaceNames: ["Neptuo.TemplateEngine.Publishing.Templates.DataSources.IArticleTagDataSourceFilter"],
    Kind: "Class",
    definition: {
        ctor: function (modelBinder, urlProvider){
            this._Key = null;
            this._Name = null;
            this._UrlPart = null;
            Neptuo.TemplateEngine.Templates.DataSources.FullDataSourceProxy$2.ctor.call(this, Neptuo.TemplateEngine.Publishing.ArticleTagListResult.ctor, Neptuo.TemplateEngine.Publishing.ViewModels.ArticleTagEditViewModel.ctor, modelBinder, urlProvider, Neptuo.TemplateEngine.Publishing.Templates.DataSources.ArticleTagDataSource.GetFilterListProperties(), Neptuo.TemplateEngine.Publishing.Templates.DataSources.ArticleTagDataSource.GetFilterSingleProperties());
        },
        Key$$: "System.Collections.Generic.IEnumerable`1[[System.Int32]]",
        get_Key: function (){
            return this._Key;
        },
        set_Key: function (value){
            this._Key = value;
        },
        Name$$: "System.String",
        get_Name: function (){
            return this._Name;
        },
        set_Name: function (value){
            this._Name = value;
        },
        UrlPart$$: "System.String",
        get_UrlPart: function (){
            return this._UrlPart;
        },
        set_UrlPart: function (value){
            this._UrlPart = value;
        },
        OnGetItem: function (callback){
            if (this.get_Key() == null){
                var model = new Neptuo.TemplateEngine.Publishing.ViewModels.ArticleTagEditViewModel.ctor();
                model = Neptuo.TemplateEngine.Providers.ModelBinders.ModelBinderExtensions.Bind$1$$IModelBinder$$T(Neptuo.TemplateEngine.Publishing.ViewModels.ArticleTagEditViewModel.ctor, this.get_ModelBinder(), model);
                callback(model);
                return true;
            }
            return false;
        }
    },
    ctors: [{
        name: "ctor",
        parameters: ["Neptuo.TemplateEngine.Providers.ModelBinders.IModelBinder", "Neptuo.Templates.IVirtualUrlProvider"]
    }
    ],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Publishing$Templates$DataSources$ArticleTagDataSource);
var Neptuo$TemplateEngine$Publishing$Templates$DataSources$ArticleLineDataSource = {
    fullname: "Neptuo.TemplateEngine.Publishing.Templates.DataSources.ArticleLineDataSource",
    baseTypeName: "Neptuo.TemplateEngine.Templates.DataSources.FullDataSourceProxy$2",
    staticDefinition: {
        GetFilterListProperties: function (){
            return (function (){
                var $v3 = new System.Collections.Generic.List$1.ctor(System.String.ctor);
                $v3.Add("Key");
                $v3.Add("Name");
                $v3.Add("UrlPart");
                return $v3;
            })();
        },
        GetFilterSingleProperties: function (){
            return (function (){
                var $v4 = new System.Collections.Generic.List$1.ctor(System.String.ctor);
                $v4.Add("Key");
                return $v4;
            })();
        }
    },
    assemblyName: "Neptuo.TemplateEngine.Publishing.Client",
    interfaceNames: ["Neptuo.TemplateEngine.Publishing.Templates.DataSources.IArticleLineDataSourceFilter"],
    Kind: "Class",
    definition: {
        ctor: function (modelBinder, urlProvider){
            this._Key = null;
            this._Name = null;
            this._UrlPart = null;
            Neptuo.TemplateEngine.Templates.DataSources.FullDataSourceProxy$2.ctor.call(this, Neptuo.TemplateEngine.Publishing.ArticleLineListResult.ctor, Neptuo.TemplateEngine.Publishing.ViewModels.ArticleLineEditViewModel.ctor, modelBinder, urlProvider, Neptuo.TemplateEngine.Publishing.Templates.DataSources.ArticleLineDataSource.GetFilterListProperties(), Neptuo.TemplateEngine.Publishing.Templates.DataSources.ArticleLineDataSource.GetFilterSingleProperties());
        },
        Key$$: "System.Nullable`1[[System.Int32]]",
        get_Key: function (){
            return this._Key;
        },
        set_Key: function (value){
            this._Key = value;
        },
        Name$$: "System.String",
        get_Name: function (){
            return this._Name;
        },
        set_Name: function (value){
            this._Name = value;
        },
        UrlPart$$: "System.String",
        get_UrlPart: function (){
            return this._UrlPart;
        },
        set_UrlPart: function (value){
            this._UrlPart = value;
        },
        OnGetItem: function (callback){
            if (this.get_Key() == null){
                var model = new Neptuo.TemplateEngine.Publishing.ViewModels.ArticleLineEditViewModel.ctor();
                model = Neptuo.TemplateEngine.Providers.ModelBinders.ModelBinderExtensions.Bind$1$$IModelBinder$$T(Neptuo.TemplateEngine.Publishing.ViewModels.ArticleLineEditViewModel.ctor, this.get_ModelBinder(), model);
                callback(model);
                return true;
            }
            return false;
        }
    },
    ctors: [{
        name: "ctor",
        parameters: ["Neptuo.TemplateEngine.Providers.ModelBinders.IModelBinder", "Neptuo.Templates.IVirtualUrlProvider"]
    }
    ],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Publishing$Templates$DataSources$ArticleLineDataSource);
var Neptuo$TemplateEngine$Publishing$Templates$DataSources$ArticleDataSource = {
    fullname: "Neptuo.TemplateEngine.Publishing.Templates.DataSources.ArticleDataSource",
    baseTypeName: "Neptuo.TemplateEngine.Templates.DataSources.FullDataSourceProxy$2",
    staticDefinition: {
        GetFilterListProperties: function (){
            return (function (){
                var $v5 = new System.Collections.Generic.List$1.ctor(System.String.ctor);
                $v5.Add("Key");
                $v5.Add("LineKey");
                $v5.Add("TagKey");
                $v5.Add("IsIncludeHidden");
                $v5.Add("Title");
                $v5.Add("UrlPart");
                return $v5;
            })();
        },
        GetFilterSingleProperties: function (){
            return (function (){
                var $v6 = new System.Collections.Generic.List$1.ctor(System.String.ctor);
                $v6.Add("Key");
                return $v6;
            })();
        }
    },
    assemblyName: "Neptuo.TemplateEngine.Publishing.Client",
    interfaceNames: ["Neptuo.TemplateEngine.Publishing.Templates.DataSources.IArticleDataSourceFilter"],
    Kind: "Class",
    definition: {
        ctor: function (modelBinder, urlProvider){
            this._Key = null;
            this._LineKey = null;
            this._TagKey = null;
            this._IsIncludeHidden = false;
            this._Title = null;
            this._UrlPart = null;
            Neptuo.TemplateEngine.Templates.DataSources.FullDataSourceProxy$2.ctor.call(this, Neptuo.TemplateEngine.Publishing.ArticleListResult.ctor, Neptuo.TemplateEngine.Publishing.ViewModels.ArticleEditViewModel.ctor, modelBinder, urlProvider, Neptuo.TemplateEngine.Publishing.Templates.DataSources.ArticleDataSource.GetFilterListProperties(), Neptuo.TemplateEngine.Publishing.Templates.DataSources.ArticleDataSource.GetFilterSingleProperties());
        },
        Key$$: "System.Nullable`1[[System.Int32]]",
        get_Key: function (){
            return this._Key;
        },
        set_Key: function (value){
            this._Key = value;
        },
        LineKey$$: "System.Nullable`1[[System.Int32]]",
        get_LineKey: function (){
            return this._LineKey;
        },
        set_LineKey: function (value){
            this._LineKey = value;
        },
        TagKey$$: "System.Nullable`1[[System.Int32]]",
        get_TagKey: function (){
            return this._TagKey;
        },
        set_TagKey: function (value){
            this._TagKey = value;
        },
        IsIncludeHidden$$: "System.Boolean",
        get_IsIncludeHidden: function (){
            return this._IsIncludeHidden;
        },
        set_IsIncludeHidden: function (value){
            this._IsIncludeHidden = value;
        },
        Title$$: "System.String",
        get_Title: function (){
            return this._Title;
        },
        set_Title: function (value){
            this._Title = value;
        },
        UrlPart$$: "System.String",
        get_UrlPart: function (){
            return this._UrlPart;
        },
        set_UrlPart: function (value){
            this._UrlPart = value;
        },
        OnGetItem: function (callback){
            if (this.get_Key() == null){
                var model = new Neptuo.TemplateEngine.Publishing.ViewModels.ArticleLineEditViewModel.ctor();
                model = Neptuo.TemplateEngine.Providers.ModelBinders.ModelBinderExtensions.Bind$1$$IModelBinder$$T(Neptuo.TemplateEngine.Publishing.ViewModels.ArticleLineEditViewModel.ctor, this.get_ModelBinder(), model);
                callback(model);
                return true;
            }
            return false;
        }
    },
    ctors: [{
        name: "ctor",
        parameters: ["Neptuo.TemplateEngine.Providers.ModelBinders.IModelBinder", "Neptuo.Templates.IVirtualUrlProvider"]
    }
    ],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Publishing$Templates$DataSources$ArticleDataSource);

