/* Generated by SharpKit 5 v5.3.6 */

if (typeof(JsTypes) == "undefined")
    var JsTypes = [];
var Neptuo$TemplateEngine$Publishing$Bootstrap$PublishingBootstrapTask = {
    fullname: "Neptuo.TemplateEngine.Publishing.Bootstrap.PublishingBootstrapTask",
    baseTypeName: "System.Object",
    assemblyName: "Neptuo.TemplateEngine.Publishing.Client",
    interfaceNames: ["Neptuo.Bootstrap.IBootstrapTask"],
    Kind: "Class",
    definition: {
        ctor: function (){
            System.Object.ctor.call(this);
        },
        Initialize: function (){
        }
    },
    ctors: [{
        name: "ctor",
        parameters: []
    }
    ],
    IsAbstract: false
};
JsTypes.push(Neptuo$TemplateEngine$Publishing$Bootstrap$PublishingBootstrapTask);

